### ISSUE TITLE
Option to customize animations duration

### ISSUE THREAD

**Issue by lwouis** [HitcherUK/skin.copacetic#9]
Hi,

First of all, thank you very much for this skin. It is incredibly well-thought and elegant. Thank you for sharing your work with all of us.

When going from one place to the other in Kodi, sometimes I know exactly where I want to go, but I'm slowed down by waiting for fade-in animations. Do you think it would be possible to add an option to customize the duration, or a toggle to simply disable animations?

Thank you 🙇

**Comment by Hitcher** [comment]
https://github.com/realcopacetic/skin.copacetic
